{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import logging\n",
    "import boto3\n",
    "import pandas as pd\n",
    "import datetime\n",
    "import io\n",
    "\n",
    "service_name = \"s3\"\n",
    "region_name = \"ap-south-1\"\n",
    "aws_access_key_id = \"AKIAVLYDFAIT7MRVU3KK\"\n",
    "aws_secret_access_key = \"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\"\n",
    "\n",
    "\n",
    "logger = logging.getLogger()\n",
    "logger.setLevel(logging.INFO)\n",
    "def generate_error_response(body):\n",
    "    response = dict()\n",
    "    response['statusCode'] = 404\n",
    "    response['headers'] = {\n",
    "        'Access-Control-Allow-Headers': 'application/json',\n",
    "        'Access-Control-Allow-Origin': '*',\n",
    "        'Access-Control-Allow-Methods': 'OPTIONS,POST,GET'\n",
    "    }\n",
    "    response['body'] = str(body)\n",
    "    return response\n",
    "def generate_right_response(body):\n",
    "    response = dict()\n",
    "    response['statusCode'] = 200\n",
    "    response['headers'] = {\n",
    "        'Access-Control-Allow-Headers': 'application/json',\n",
    "        'Access-Control-Allow-Origin': '*',\n",
    "        'Access-Control-Allow-Methods': 'OPTIONS,POST,GET'\n",
    "    }\n",
    "    try:\n",
    "        if type(body) != str:\n",
    "            body = json.dumps(body, indent=4)\n",
    "        response['body'] = body\n",
    "    except Exception as e:\n",
    "        response['statusCode'] = 404\n",
    "        response['body'] = e\n",
    "    return response\n",
    "\n",
    "\n",
    "def get_score(acc_no,amount,payee_acc_num,payer_address,mdf):\n",
    "    payer_address=payer_address.split('@')[1]\n",
    "    tdf=None\n",
    "    try:\n",
    "        tdf=mdf.loc[acc_no]\n",
    "    except Exception as e:\n",
    "        return 50\n",
    "\n",
    "    score=0\n",
    "\n",
    "\n",
    "    last=tdf[\"Recent Transaction\"]\n",
    "    last=str(last).split('.')[0]\n",
    "    last=datetime.datetime.strptime(str(last), '%Y-%m-%d %H:%M:%S')\n",
    "    last_payee=tdf[\"Last Payee Account Number\"]\n",
    "    now=datetime.datetime.now()\n",
    "    curr_time=now.time()\n",
    "    d=now-last\n",
    "    if d.days==0:\n",
    "        time_diff=d.seconds//60\n",
    "        if time_diff<=4 and payee_acc_num==last_payee:\n",
    "            score=20\n",
    "        else:\n",
    "            score=2\n",
    "\n",
    "    upi=eval(tdf[\"UPI\"])\n",
    "    if payer_address in upi:\n",
    "        score+=upi[payer_address]\n",
    "    else:\n",
    "        score+=10.0\n",
    "\n",
    "    timeslot=\"TimeSlot\"\n",
    "    now=datetime.datetime.now()\n",
    "    curr_time=now.time()\n",
    "    if curr_time>=datetime.time(0, 0, 0) and curr_time<=datetime.time(3, 59, 59):\n",
    "        timeslot=\"TimeSlot1\"\n",
    "    elif curr_time>=datetime.time(4, 0, 0) and curr_time<=datetime.time(7, 59, 59):\n",
    "        timeslot=\"TimeSlot2\"\n",
    "    elif curr_time>=datetime.time(8, 0, 0) and curr_time<=datetime.time(11, 59, 59):\n",
    "        timeslot=\"TimeSlot3\"\n",
    "    elif curr_time>=datetime.time(12, 0, 0) and curr_time<=datetime.time(15, 59, 59):\n",
    "        timeslot=\"TimeSlot4\"\n",
    "    elif curr_time>=datetime.time(16, 0, 0) and curr_time<=datetime.time(19, 59, 59):\n",
    "        timeslot=\"TimeSlot5\"\n",
    "    else:\n",
    "        timeslot=\"TimeSlot6\"\n",
    "\n",
    "    score+=tdf[timeslot]\n",
    "\n",
    "    amountslot=\"Amount\"\n",
    "    k=0\n",
    "    for i in range(0, 100000, 5000):\n",
    "        minimum = i\n",
    "        maximum = i+4999\n",
    "        k=k+1\n",
    "        if amount>=minimum and amount<=maximum:\n",
    "            amountslot=amountslot+str(k)\n",
    "            break\n",
    "    score+=tdf[amountslot]\n",
    "\n",
    "    tdf[\"Recent Transaction\"]=str(now)\n",
    "    tdf[\"Last Payee Account Number\"]=payee_acc_num\n",
    "     mdf.loc[acc_no]=tdf\n",
    "\n",
    "    return [score,mdf]\n",
    "\n",
    "\n",
    "\n",
    "def lambda_handler(event, context):\n",
    "    logger.info(event)\n",
    "    method = event['httpMethod']\n",
    "    resource = event['resource']\n",
    "    try:\n",
    "        if method == \"POST\":\n",
    "            s3 = boto3.resource(\n",
    "            service_name = service_name,\n",
    "            region_name = region_name,\n",
    "            aws_access_key_id = aws_access_key_id,\n",
    "            aws_secret_access_key = aws_secret_access_key\n",
    "            )\n",
    "            file = s3.Bucket('myfrmbucket').Object('df.pkl').get()\n",
    "            # print(file)\n",
    "            mdf=pd.read_pickle(io.BytesIO(file['Body'].read()))\n",
    "            mdf=mdf.set_index(\"Payer Account Number\")\n",
    "\n",
    "            data = json.loads(event['body'])\n",
    "            payer_acc_no=data[\"payer_acc_no\"]\n",
    "            payee_acc_no=data[\"payee_acc_no\"]\n",
    "            payer_address=data[\"payer_address\"]\n",
    "            amount=data[\"amount\"]\n",
    "            \n",
    "            # mdf.to_pickle('/tmp/df.pkl')\n",
    "            # s3.Bucket('myfrmbucket').upload_file(Filename='/tmp/df.pkl', Key='df.pkl')\n",
    "            \n",
    "            result=get_score(payer_acc_no,amount,payee_acc_no,payer_address,mdf)\n",
    "            score = result[0]\n",
    "            mdf = result[1]\n",
    "             return generate_right_response(score)\n",
    "        else:\n",
    "          return generate_right_response(\"Method not allowed\")\n",
    "    except Exception as e:\n",
    "        return generate_right_response(str(e))"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "collapsed_sections": [],
   "name": "07/07/2022.ipynb",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
